/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ChatNest API
 * API for ChatNest chat application
 * OpenAPI spec version: 1.0.0
 */
export interface LastMessageDto {
  text?: string;
  image?: string;
  /** Timestamp of the last message */
  createdAt?: string;
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
export interface PickIUserDTOExcludeKeyofIUserDTOPassword {
  /** User email */
  email: string;
  /** User fullname */
  fullname: string;
  /** User profile picture */
  profilePic: string;
  /** MongoDB Object ID */
  _id: string;
  createdAt: string;
  updatedAt: string;
}

export interface UserResponseDtoWithLastMessage {
  /** User email */
  email: string;
  /** User fullname */
  fullname: string;
  /** User profile picture */
  profilePic: string;
  /** MongoDB Object ID */
  _id: string;
  createdAt: string;
  updatedAt: string;
  lastMessage?: LastMessageDto;
  unreadCount?: number;
}

export type MongooseTypesObjectId = string;

export interface ReactionDto {
  emoji: string;
  userId: string;
}

export interface MessageResponseDto {
  /** MongoDB Object ID */
  _id: string;
  createdAt: string;
  updatedAt: string;
  /** Message content */
  text?: string;
  /** Message image URL */
  image?: string;
  /** Sender's user ID */
  senderId: MongooseTypesObjectId;
  /** Receiver's user ID */
  receiverId: MongooseTypesObjectId;
  isRead: boolean;
  reactions: ReactionDto[];
}

export interface UserResponseDto {
  /** User email */
  email: string;
  /** User fullname */
  fullname: string;
  /** User profile picture */
  profilePic: string;
  /** MongoDB Object ID */
  _id: string;
  createdAt: string;
  updatedAt: string;
}

export interface SearchMessageResultDto {
  /** MongoDB Object ID */
  _id: string;
  createdAt: string;
  /** Message content */
  text: string;
  /** Sender's user ID */
  senderId: MongooseTypesObjectId;
  /** Receiver's user ID */
  receiverId: MongooseTypesObjectId;
  otherUser: UserResponseDto;
}

export interface GroupLastMessageDto {
  text?: string;
  image?: string;
  createdAt?: string;
  senderName?: string;
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
export interface PickIUserDTOFullnameOrProfilePic {
  /** User fullname */
  fullname: string;
  /** User profile picture */
  profilePic: string;
}

export type GroupMemberDto = PickIUserDTOFullnameOrProfilePic;

export interface GroupResponseDto {
  /** MongoDB Object ID */
  _id: string;
  createdAt: string;
  updatedAt: string;
  name: string;
  avatar?: string;
  ownerId: MongooseTypesObjectId;
  members: PickIUserDTOFullnameOrProfilePic[];
  lastMessage?: GroupLastMessageDto;
  unreadCount?: number;
}

export interface CreateGroupBody {
  name: string;
  memberIds: string[];
}

export interface GroupMessageResponseDto {
  /** MongoDB Object ID */
  _id: string;
  createdAt: string;
  updatedAt: string;
  groupId: MongooseTypesObjectId;
  senderId: MongooseTypesObjectId;
  text?: string;
  image?: string;
  reactions: ReactionDto[];
  readBy: MongooseTypesObjectId[];
  sender: PickIUserDTOFullnameOrProfilePic;
}

export interface SearchGroupMessageResultDto {
  /** MongoDB Object ID */
  _id: string;
  /** Message content */
  text?: string;
  /** Sender's user ID */
  senderId: string;
  /** Group ID */
  groupId: string;
  /** Group name */
  groupName: string;
  /** Sender's full name */
  senderName: string;
  createdAt: string;
}

export interface IUser {
  /** User email */
  email: string;
  /** User fullname */
  fullname: string;
  /** User password */
  password: string;
  /** User profile picture */
  profilePic?: string;
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
export interface PickIUserEmailOrPassword {
  /** User password */
  password: string;
  /** User email */
  email: string;
}

export type MarkReadBody = {
  messageIds: string[];
};

/**
 * @nullable
 */
export type MarkRead200 = typeof MarkRead200[keyof typeof MarkRead200] | null;


export const MarkRead200 = {
} as const;

export type SearchParams = {
q: string;
};

export type PostMessageBody = {
  text?: string;
  image?: Blob;
};

/**
 * @nullable
 */
export type DissolveGroup200 = typeof DissolveGroup200[keyof typeof DissolveGroup200] | null;


export const DissolveGroup200 = {
} as const;

export type UpdateGroupAvatarBody = {
  image?: Blob;
};

export type MarkGroupMessagesReadBody = {
  messageIds: string[];
};

/**
 * @nullable
 */
export type MarkGroupMessagesRead200 = typeof MarkGroupMessagesRead200[keyof typeof MarkGroupMessagesRead200] | null;


export const MarkGroupMessagesRead200 = {
} as const;

export type SearchGroupMessagesParams = {
q: string;
};

export type SendGroupMessageBody = {
  text?: string;
  image?: Blob;
};

/**
 * @nullable
 */
export type Logout200 = typeof Logout200[keyof typeof Logout200] | null;


export const Logout200 = {
} as const;

export type UpdateProfileBody = {
  file: Blob;
};

