/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ChatNest API
 * API for ChatNest chat application
 * OpenAPI spec version: 1.0.0
 */
export interface UserResponseDto {
  /** User email */
  email: string;
  /** User fullname */
  fullname: string;
  /** User password */
  password: string;
  /** User profile picture */
  profilePic?: string;
  /** MongoDB Object ID */
  _id: string;
  /** Created timestamp */
  createdAt: string;
  /** Updated timestamp */
  updatedAt: string;
}

export interface ApiResponseUserResponseDtoArray {
  code: number;
  message: string;
  data: UserResponseDto[];
}

export type MongooseTypesObjectId = string;

export interface MessageResponseDto {
  /** Message content */
  text?: string;
  /** Message image URL */
  image?: string;
  /** Sender's user ID */
  senderId: MongooseTypesObjectId;
  /** Receiver's user ID */
  receiverId: MongooseTypesObjectId;
  /** MongoDB Object ID */
  _id: string;
  /** Created timestamp */
  createdAt: string;
  /** Updated timestamp */
  updatedAt: string;
}

export interface ApiResponseMessageResponseDtoArray {
  code: number;
  message: string;
  data: MessageResponseDto[];
}

export interface ApiResponseMessageResponseDto {
  code: number;
  message: string;
  data: MessageResponseDto;
}

/**
 * Make all properties in T optional
 */
export interface PartialIMessageDTO {
  /** Message content */
  text?: string;
  /** Message image URL */
  image?: string;
  /** Sender's user ID */
  senderId?: MongooseTypesObjectId;
  /** Receiver's user ID */
  receiverId?: MongooseTypesObjectId;
}

export interface ApiResponseUserResponseDto {
  code: number;
  message: string;
  data: UserResponseDto;
}

export interface IUserDTO {
  /** User email */
  email: string;
  /** User fullname */
  fullname: string;
  /** User password */
  password: string;
  /** User profile picture */
  profilePic?: string;
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
export interface PickIUserDTOEmailOrPassword {
  /** User email */
  email: string;
  /** User password */
  password: string;
}

/**
 * @nullable
 */
export type ApiResponseNullData = typeof ApiResponseNullData[keyof typeof ApiResponseNullData] | null;


export const ApiResponseNullData = {
} as const;

export interface ApiResponseNull {
  code: number;
  message: string;
  /** @nullable */
  data: ApiResponseNullData;
}

/**
 * Make all properties in T optional
 */
export interface PartialIUserDTO {
  /** User email */
  email?: string;
  /** User fullname */
  fullname?: string;
  /** User password */
  password?: string;
  /** User profile picture */
  profilePic?: string;
}

export type HttpStatus = typeof HttpStatus[keyof typeof HttpStatus];


export const HttpStatus = {
  NUMBER_200: 200,
  NUMBER_201: 201,
  NUMBER_400: 400,
  NUMBER_401: 401,
  NUMBER_403: 403,
  NUMBER_404: 404,
  NUMBER_500: 500,
} as const;

export type CheckAuth200 = {
  data: unknown;
  message: string;
  code: HttpStatus;
};

