/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ChatNest API
 * API for ChatNest chat application
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ConversationResponseDto,
  CreateGroupRequest,
  DissolveConversation200,
  FindOrCreateDmRequest,
  MessageResponseDto,
  SearchMessageResultDto,
  SearchParams,
  UpdateGroupAvatarBody,
  UploadImageBody,
  UploadImageResponse
} from './chatNestAPI.schemas';

import { request } from '../request';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetConversationListUrl = () => {


  

  return `/api/conversation/list`
}

export const getConversationList = async ( options?: RequestInit): Promise<ConversationResponseDto[]> => {
  
  return request<ConversationResponseDto[]>(getGetConversationListUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetConversationListQueryKey = () => {
    return [
    `/api/conversation/list`
    ] as const;
    }

    
export const getGetConversationListQueryOptions = <TData = Awaited<ReturnType<typeof getConversationList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConversationList>>, TError, TData>>, request?: SecondParameter<typeof request>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetConversationListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getConversationList>>> = ({ signal }) => getConversationList({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getConversationList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetConversationListQueryResult = NonNullable<Awaited<ReturnType<typeof getConversationList>>>
export type GetConversationListQueryError = unknown


export function useGetConversationList<TData = Awaited<ReturnType<typeof getConversationList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConversationList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConversationList>>,
          TError,
          Awaited<ReturnType<typeof getConversationList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConversationList<TData = Awaited<ReturnType<typeof getConversationList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConversationList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConversationList>>,
          TError,
          Awaited<ReturnType<typeof getConversationList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConversationList<TData = Awaited<ReturnType<typeof getConversationList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConversationList>>, TError, TData>>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetConversationList<TData = Awaited<ReturnType<typeof getConversationList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConversationList>>, TError, TData>>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetConversationListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getFindOrCreateDmUrl = () => {


  

  return `/api/conversation/dm`
}

export const findOrCreateDm = async (findOrCreateDmRequest: FindOrCreateDmRequest, options?: RequestInit): Promise<ConversationResponseDto> => {
  
  return request<ConversationResponseDto>(getFindOrCreateDmUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      findOrCreateDmRequest,)
  }
);}




export const getFindOrCreateDmMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof findOrCreateDm>>, TError,{data: FindOrCreateDmRequest}, TContext>, request?: SecondParameter<typeof request>}
): UseMutationOptions<Awaited<ReturnType<typeof findOrCreateDm>>, TError,{data: FindOrCreateDmRequest}, TContext> => {

const mutationKey = ['findOrCreateDm'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof findOrCreateDm>>, {data: FindOrCreateDmRequest}> = (props) => {
          const {data} = props ?? {};

          return  findOrCreateDm(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type FindOrCreateDmMutationResult = NonNullable<Awaited<ReturnType<typeof findOrCreateDm>>>
    export type FindOrCreateDmMutationBody = FindOrCreateDmRequest
    export type FindOrCreateDmMutationError = unknown

    export const useFindOrCreateDm = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof findOrCreateDm>>, TError,{data: FindOrCreateDmRequest}, TContext>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof findOrCreateDm>>,
        TError,
        {data: FindOrCreateDmRequest},
        TContext
      > => {
      return useMutation(getFindOrCreateDmMutationOptions(options), queryClient);
    }
    export const getCreateGroupUrl = () => {


  

  return `/api/conversation/group`
}

export const createGroup = async (createGroupRequest: CreateGroupRequest, options?: RequestInit): Promise<ConversationResponseDto> => {
  
  return request<ConversationResponseDto>(getCreateGroupUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createGroupRequest,)
  }
);}




export const getCreateGroupMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGroup>>, TError,{data: CreateGroupRequest}, TContext>, request?: SecondParameter<typeof request>}
): UseMutationOptions<Awaited<ReturnType<typeof createGroup>>, TError,{data: CreateGroupRequest}, TContext> => {

const mutationKey = ['createGroup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createGroup>>, {data: CreateGroupRequest}> = (props) => {
          const {data} = props ?? {};

          return  createGroup(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateGroupMutationResult = NonNullable<Awaited<ReturnType<typeof createGroup>>>
    export type CreateGroupMutationBody = CreateGroupRequest
    export type CreateGroupMutationError = unknown

    export const useCreateGroup = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGroup>>, TError,{data: CreateGroupRequest}, TContext>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createGroup>>,
        TError,
        {data: CreateGroupRequest},
        TContext
      > => {
      return useMutation(getCreateGroupMutationOptions(options), queryClient);
    }
    export const getDissolveConversationUrl = (id: string,) => {


  

  return `/api/conversation/${id}`
}

export const dissolveConversation = async (id: string, options?: RequestInit): Promise<DissolveConversation200> => {
  
  return request<DissolveConversation200>(getDissolveConversationUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDissolveConversationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dissolveConversation>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof request>}
): UseMutationOptions<Awaited<ReturnType<typeof dissolveConversation>>, TError,{id: string}, TContext> => {

const mutationKey = ['dissolveConversation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dissolveConversation>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  dissolveConversation(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DissolveConversationMutationResult = NonNullable<Awaited<ReturnType<typeof dissolveConversation>>>
    
    export type DissolveConversationMutationError = unknown

    export const useDissolveConversation = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dissolveConversation>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof dissolveConversation>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDissolveConversationMutationOptions(options), queryClient);
    }
    export const getUpdateGroupAvatarUrl = (id: string,) => {


  

  return `/api/conversation/${id}/avatar`
}

export const updateGroupAvatar = async (id: string,
    updateGroupAvatarBody?: UpdateGroupAvatarBody, options?: RequestInit): Promise<ConversationResponseDto> => {
    const formData = new FormData();
if(updateGroupAvatarBody?.image !== undefined) {
 formData.append(`image`, updateGroupAvatarBody.image);
 }

  return request<ConversationResponseDto>(getUpdateGroupAvatarUrl(id),
  {      
    ...options,
    method: 'PUT'
    ,
    body: 
      formData,
  }
);}




export const getUpdateGroupAvatarMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateGroupAvatar>>, TError,{id: string;data: UpdateGroupAvatarBody}, TContext>, request?: SecondParameter<typeof request>}
): UseMutationOptions<Awaited<ReturnType<typeof updateGroupAvatar>>, TError,{id: string;data: UpdateGroupAvatarBody}, TContext> => {

const mutationKey = ['updateGroupAvatar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateGroupAvatar>>, {id: string;data: UpdateGroupAvatarBody}> = (props) => {
          const {id,data} = props ?? {};

          return  updateGroupAvatar(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateGroupAvatarMutationResult = NonNullable<Awaited<ReturnType<typeof updateGroupAvatar>>>
    export type UpdateGroupAvatarMutationBody = UpdateGroupAvatarBody
    export type UpdateGroupAvatarMutationError = unknown

    export const useUpdateGroupAvatar = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateGroupAvatar>>, TError,{id: string;data: UpdateGroupAvatarBody}, TContext>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateGroupAvatar>>,
        TError,
        {id: string;data: UpdateGroupAvatarBody},
        TContext
      > => {
      return useMutation(getUpdateGroupAvatarMutationOptions(options), queryClient);
    }
    export const getGetMessagesUrl = (id: string,) => {


  

  return `/api/conversation/${id}/messages`
}

export const getMessages = async (id: string, options?: RequestInit): Promise<MessageResponseDto[]> => {
  
  return request<MessageResponseDto[]>(getGetMessagesUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetMessagesQueryKey = (id: string,) => {
    return [
    `/api/conversation/${id}/messages`
    ] as const;
    }

    
export const getGetMessagesQueryOptions = <TData = Awaited<ReturnType<typeof getMessages>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessages>>, TError, TData>>, request?: SecondParameter<typeof request>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMessagesQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMessages>>> = ({ signal }) => getMessages(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMessages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMessagesQueryResult = NonNullable<Awaited<ReturnType<typeof getMessages>>>
export type GetMessagesQueryError = unknown


export function useGetMessages<TData = Awaited<ReturnType<typeof getMessages>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessages>>,
          TError,
          Awaited<ReturnType<typeof getMessages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessages<TData = Awaited<ReturnType<typeof getMessages>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessages>>,
          TError,
          Awaited<ReturnType<typeof getMessages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessages<TData = Awaited<ReturnType<typeof getMessages>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessages>>, TError, TData>>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMessages<TData = Awaited<ReturnType<typeof getMessages>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessages>>, TError, TData>>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMessagesQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getUploadImageUrl = () => {


  

  return `/api/conversation/upload-image`
}

export const uploadImage = async (uploadImageBody?: UploadImageBody, options?: RequestInit): Promise<UploadImageResponse> => {
    const formData = new FormData();
if(uploadImageBody?.image !== undefined) {
 formData.append(`image`, uploadImageBody.image);
 }

  return request<UploadImageResponse>(getUploadImageUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}




export const getUploadImageMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadImage>>, TError,{data: UploadImageBody}, TContext>, request?: SecondParameter<typeof request>}
): UseMutationOptions<Awaited<ReturnType<typeof uploadImage>>, TError,{data: UploadImageBody}, TContext> => {

const mutationKey = ['uploadImage'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadImage>>, {data: UploadImageBody}> = (props) => {
          const {data} = props ?? {};

          return  uploadImage(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UploadImageMutationResult = NonNullable<Awaited<ReturnType<typeof uploadImage>>>
    export type UploadImageMutationBody = UploadImageBody
    export type UploadImageMutationError = unknown

    export const useUploadImage = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadImage>>, TError,{data: UploadImageBody}, TContext>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadImage>>,
        TError,
        {data: UploadImageBody},
        TContext
      > => {
      return useMutation(getUploadImageMutationOptions(options), queryClient);
    }
    export const getSearchUrl = (params: SearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/conversation/search?${stringifiedParams}` : `/api/conversation/search`
}

export const search = async (params: SearchParams, options?: RequestInit): Promise<SearchMessageResultDto[]> => {
  
  return request<SearchMessageResultDto[]>(getSearchUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getSearchQueryKey = (params?: SearchParams,) => {
    return [
    `/api/conversation/search`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getSearchQueryOptions = <TData = Awaited<ReturnType<typeof search>>, TError = unknown>(params: SearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>>, request?: SecondParameter<typeof request>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof search>>> = ({ signal }) => search(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchQueryResult = NonNullable<Awaited<ReturnType<typeof search>>>
export type SearchQueryError = unknown


export function useSearch<TData = Awaited<ReturnType<typeof search>>, TError = unknown>(
 params: SearchParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof search>>,
          TError,
          Awaited<ReturnType<typeof search>>
        > , 'initialData'
      >, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearch<TData = Awaited<ReturnType<typeof search>>, TError = unknown>(
 params: SearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof search>>,
          TError,
          Awaited<ReturnType<typeof search>>
        > , 'initialData'
      >, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearch<TData = Awaited<ReturnType<typeof search>>, TError = unknown>(
 params: SearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSearch<TData = Awaited<ReturnType<typeof search>>, TError = unknown>(
 params: SearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




