/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ChatNest API
 * API for ChatNest chat application
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateGroupBody,
  DissolveGroup200,
  GroupMessageResponseDto,
  GroupResponseDto,
  MarkGroupMessagesRead200,
  MarkGroupMessagesReadBody,
  SearchGroupMessageResultDto,
  SearchGroupMessagesParams,
  SendGroupMessageBody,
  UpdateGroupAvatarBody
} from './chatNestAPI.schemas';

import { request } from '../request';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetGroupListUrl = () => {


  

  return `/api/group/list`
}

export const getGroupList = async ( options?: RequestInit): Promise<GroupResponseDto[]> => {
  
  return request<GroupResponseDto[]>(getGetGroupListUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetGroupListQueryKey = () => {
    return [
    `/api/group/list`
    ] as const;
    }

    
export const getGetGroupListQueryOptions = <TData = Awaited<ReturnType<typeof getGroupList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupList>>, TError, TData>>, request?: SecondParameter<typeof request>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGroupListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGroupList>>> = ({ signal }) => getGroupList({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGroupList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGroupListQueryResult = NonNullable<Awaited<ReturnType<typeof getGroupList>>>
export type GetGroupListQueryError = unknown


export function useGetGroupList<TData = Awaited<ReturnType<typeof getGroupList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGroupList>>,
          TError,
          Awaited<ReturnType<typeof getGroupList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGroupList<TData = Awaited<ReturnType<typeof getGroupList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGroupList>>,
          TError,
          Awaited<ReturnType<typeof getGroupList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGroupList<TData = Awaited<ReturnType<typeof getGroupList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupList>>, TError, TData>>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetGroupList<TData = Awaited<ReturnType<typeof getGroupList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupList>>, TError, TData>>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGroupListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getCreateGroupUrl = () => {


  

  return `/api/group/create`
}

export const createGroup = async (createGroupBody: CreateGroupBody, options?: RequestInit): Promise<GroupResponseDto> => {
  
  return request<GroupResponseDto>(getCreateGroupUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createGroupBody,)
  }
);}




export const getCreateGroupMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGroup>>, TError,{data: CreateGroupBody}, TContext>, request?: SecondParameter<typeof request>}
): UseMutationOptions<Awaited<ReturnType<typeof createGroup>>, TError,{data: CreateGroupBody}, TContext> => {

const mutationKey = ['createGroup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createGroup>>, {data: CreateGroupBody}> = (props) => {
          const {data} = props ?? {};

          return  createGroup(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateGroupMutationResult = NonNullable<Awaited<ReturnType<typeof createGroup>>>
    export type CreateGroupMutationBody = CreateGroupBody
    export type CreateGroupMutationError = unknown

    export const useCreateGroup = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGroup>>, TError,{data: CreateGroupBody}, TContext>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createGroup>>,
        TError,
        {data: CreateGroupBody},
        TContext
      > => {
      return useMutation(getCreateGroupMutationOptions(options), queryClient);
    }
    export const getDissolveGroupUrl = (id: string,) => {


  

  return `/api/group/${id}/dissolve`
}

export const dissolveGroup = async (id: string, options?: RequestInit): Promise<DissolveGroup200> => {
  
  return request<DissolveGroup200>(getDissolveGroupUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDissolveGroupMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dissolveGroup>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof request>}
): UseMutationOptions<Awaited<ReturnType<typeof dissolveGroup>>, TError,{id: string}, TContext> => {

const mutationKey = ['dissolveGroup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dissolveGroup>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  dissolveGroup(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DissolveGroupMutationResult = NonNullable<Awaited<ReturnType<typeof dissolveGroup>>>
    
    export type DissolveGroupMutationError = unknown

    export const useDissolveGroup = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dissolveGroup>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof dissolveGroup>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDissolveGroupMutationOptions(options), queryClient);
    }
    export const getUpdateGroupAvatarUrl = (id: string,) => {


  

  return `/api/group/${id}/avatar`
}

export const updateGroupAvatar = async (id: string,
    updateGroupAvatarBody?: UpdateGroupAvatarBody, options?: RequestInit): Promise<GroupResponseDto> => {
    const formData = new FormData();
if(updateGroupAvatarBody?.image !== undefined) {
 formData.append(`image`, updateGroupAvatarBody.image);
 }

  return request<GroupResponseDto>(getUpdateGroupAvatarUrl(id),
  {      
    ...options,
    method: 'PUT'
    ,
    body: 
      formData,
  }
);}




export const getUpdateGroupAvatarMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateGroupAvatar>>, TError,{id: string;data: UpdateGroupAvatarBody}, TContext>, request?: SecondParameter<typeof request>}
): UseMutationOptions<Awaited<ReturnType<typeof updateGroupAvatar>>, TError,{id: string;data: UpdateGroupAvatarBody}, TContext> => {

const mutationKey = ['updateGroupAvatar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateGroupAvatar>>, {id: string;data: UpdateGroupAvatarBody}> = (props) => {
          const {id,data} = props ?? {};

          return  updateGroupAvatar(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateGroupAvatarMutationResult = NonNullable<Awaited<ReturnType<typeof updateGroupAvatar>>>
    export type UpdateGroupAvatarMutationBody = UpdateGroupAvatarBody
    export type UpdateGroupAvatarMutationError = unknown

    export const useUpdateGroupAvatar = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateGroupAvatar>>, TError,{id: string;data: UpdateGroupAvatarBody}, TContext>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateGroupAvatar>>,
        TError,
        {id: string;data: UpdateGroupAvatarBody},
        TContext
      > => {
      return useMutation(getUpdateGroupAvatarMutationOptions(options), queryClient);
    }
    export const getGetGroupMessagesUrl = (id: string,) => {


  

  return `/api/group/${id}/messages`
}

export const getGroupMessages = async (id: string, options?: RequestInit): Promise<GroupMessageResponseDto[]> => {
  
  return request<GroupMessageResponseDto[]>(getGetGroupMessagesUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetGroupMessagesQueryKey = (id: string,) => {
    return [
    `/api/group/${id}/messages`
    ] as const;
    }

    
export const getGetGroupMessagesQueryOptions = <TData = Awaited<ReturnType<typeof getGroupMessages>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupMessages>>, TError, TData>>, request?: SecondParameter<typeof request>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGroupMessagesQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGroupMessages>>> = ({ signal }) => getGroupMessages(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGroupMessages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGroupMessagesQueryResult = NonNullable<Awaited<ReturnType<typeof getGroupMessages>>>
export type GetGroupMessagesQueryError = unknown


export function useGetGroupMessages<TData = Awaited<ReturnType<typeof getGroupMessages>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupMessages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGroupMessages>>,
          TError,
          Awaited<ReturnType<typeof getGroupMessages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGroupMessages<TData = Awaited<ReturnType<typeof getGroupMessages>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupMessages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGroupMessages>>,
          TError,
          Awaited<ReturnType<typeof getGroupMessages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGroupMessages<TData = Awaited<ReturnType<typeof getGroupMessages>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupMessages>>, TError, TData>>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetGroupMessages<TData = Awaited<ReturnType<typeof getGroupMessages>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupMessages>>, TError, TData>>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGroupMessagesQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getMarkGroupMessagesReadUrl = (groupId: string,) => {


  

  return `/api/group/${groupId}/messages/markRead`
}

export const markGroupMessagesRead = async (groupId: string,
    markGroupMessagesReadBody: MarkGroupMessagesReadBody, options?: RequestInit): Promise<MarkGroupMessagesRead200> => {
  
  return request<MarkGroupMessagesRead200>(getMarkGroupMessagesReadUrl(groupId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      markGroupMessagesReadBody,)
  }
);}




export const getMarkGroupMessagesReadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markGroupMessagesRead>>, TError,{groupId: string;data: MarkGroupMessagesReadBody}, TContext>, request?: SecondParameter<typeof request>}
): UseMutationOptions<Awaited<ReturnType<typeof markGroupMessagesRead>>, TError,{groupId: string;data: MarkGroupMessagesReadBody}, TContext> => {

const mutationKey = ['markGroupMessagesRead'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof markGroupMessagesRead>>, {groupId: string;data: MarkGroupMessagesReadBody}> = (props) => {
          const {groupId,data} = props ?? {};

          return  markGroupMessagesRead(groupId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type MarkGroupMessagesReadMutationResult = NonNullable<Awaited<ReturnType<typeof markGroupMessagesRead>>>
    export type MarkGroupMessagesReadMutationBody = MarkGroupMessagesReadBody
    export type MarkGroupMessagesReadMutationError = unknown

    export const useMarkGroupMessagesRead = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markGroupMessagesRead>>, TError,{groupId: string;data: MarkGroupMessagesReadBody}, TContext>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof markGroupMessagesRead>>,
        TError,
        {groupId: string;data: MarkGroupMessagesReadBody},
        TContext
      > => {
      return useMutation(getMarkGroupMessagesReadMutationOptions(options), queryClient);
    }
    export const getSearchGroupMessagesUrl = (params: SearchGroupMessagesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/group/messages/search?${stringifiedParams}` : `/api/group/messages/search`
}

export const searchGroupMessages = async (params: SearchGroupMessagesParams, options?: RequestInit): Promise<SearchGroupMessageResultDto[]> => {
  
  return request<SearchGroupMessageResultDto[]>(getSearchGroupMessagesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getSearchGroupMessagesQueryKey = (params?: SearchGroupMessagesParams,) => {
    return [
    `/api/group/messages/search`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getSearchGroupMessagesQueryOptions = <TData = Awaited<ReturnType<typeof searchGroupMessages>>, TError = unknown>(params: SearchGroupMessagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchGroupMessages>>, TError, TData>>, request?: SecondParameter<typeof request>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchGroupMessagesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchGroupMessages>>> = ({ signal }) => searchGroupMessages(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchGroupMessages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchGroupMessagesQueryResult = NonNullable<Awaited<ReturnType<typeof searchGroupMessages>>>
export type SearchGroupMessagesQueryError = unknown


export function useSearchGroupMessages<TData = Awaited<ReturnType<typeof searchGroupMessages>>, TError = unknown>(
 params: SearchGroupMessagesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchGroupMessages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchGroupMessages>>,
          TError,
          Awaited<ReturnType<typeof searchGroupMessages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchGroupMessages<TData = Awaited<ReturnType<typeof searchGroupMessages>>, TError = unknown>(
 params: SearchGroupMessagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchGroupMessages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchGroupMessages>>,
          TError,
          Awaited<ReturnType<typeof searchGroupMessages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchGroupMessages<TData = Awaited<ReturnType<typeof searchGroupMessages>>, TError = unknown>(
 params: SearchGroupMessagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchGroupMessages>>, TError, TData>>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSearchGroupMessages<TData = Awaited<ReturnType<typeof searchGroupMessages>>, TError = unknown>(
 params: SearchGroupMessagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchGroupMessages>>, TError, TData>>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchGroupMessagesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getSendGroupMessageUrl = (groupId: string,) => {


  

  return `/api/group/${groupId}/message`
}

export const sendGroupMessage = async (groupId: string,
    sendGroupMessageBody?: SendGroupMessageBody, options?: RequestInit): Promise<GroupMessageResponseDto> => {
    const formData = new FormData();
if(sendGroupMessageBody?.text !== undefined) {
 formData.append(`text`, sendGroupMessageBody.text);
 }
if(sendGroupMessageBody?.image !== undefined) {
 formData.append(`image`, sendGroupMessageBody.image);
 }

  return request<GroupMessageResponseDto>(getSendGroupMessageUrl(groupId),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}




export const getSendGroupMessageMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendGroupMessage>>, TError,{groupId: string;data: SendGroupMessageBody}, TContext>, request?: SecondParameter<typeof request>}
): UseMutationOptions<Awaited<ReturnType<typeof sendGroupMessage>>, TError,{groupId: string;data: SendGroupMessageBody}, TContext> => {

const mutationKey = ['sendGroupMessage'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendGroupMessage>>, {groupId: string;data: SendGroupMessageBody}> = (props) => {
          const {groupId,data} = props ?? {};

          return  sendGroupMessage(groupId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SendGroupMessageMutationResult = NonNullable<Awaited<ReturnType<typeof sendGroupMessage>>>
    export type SendGroupMessageMutationBody = SendGroupMessageBody
    export type SendGroupMessageMutationError = unknown

    export const useSendGroupMessage = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendGroupMessage>>, TError,{groupId: string;data: SendGroupMessageBody}, TContext>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sendGroupMessage>>,
        TError,
        {groupId: string;data: SendGroupMessageBody},
        TContext
      > => {
      return useMutation(getSendGroupMessageMutationOptions(options), queryClient);
    }
    