/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ChatNest API
 * API for ChatNest chat application
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseMessageResponseDto,
  ApiResponseMessageResponseDtoArray,
  ApiResponseUserResponseDtoArray,
  PartialIMessageDTO
} from './chatNestAPI.schemas';






export type getUsersListResponse200 = {
  data: ApiResponseUserResponseDtoArray
  status: 200
}
    
export type getUsersListResponseSuccess = (getUsersListResponse200) & {
  headers: Headers;
};
;

export type getUsersListResponse = (getUsersListResponseSuccess)

export const getGetUsersListUrl = () => {


  

  return `/api/message/getUsersListWithoutCurrentUser`
}

export const getUsersList = async ( options?: RequestInit): Promise<getUsersListResponse> => {
  
  const res = await fetch(getGetUsersListUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getUsersListResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUsersListResponse
}





export const getGetUsersListQueryKey = () => {
    return [
    `/api/message/getUsersListWithoutCurrentUser`
    ] as const;
    }

    
export const getGetUsersListQueryOptions = <TData = Awaited<ReturnType<typeof getUsersList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersList>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersList>>> = ({ signal }) => getUsersList({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsersList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersListQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersList>>>
export type GetUsersListQueryError = unknown


export function useGetUsersList<TData = Awaited<ReturnType<typeof getUsersList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersList>>,
          TError,
          Awaited<ReturnType<typeof getUsersList>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersList<TData = Awaited<ReturnType<typeof getUsersList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersList>>,
          TError,
          Awaited<ReturnType<typeof getUsersList>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersList<TData = Awaited<ReturnType<typeof getUsersList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersList>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUsersList<TData = Awaited<ReturnType<typeof getUsersList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersList>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsersListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type getMessagesResponse200 = {
  data: ApiResponseMessageResponseDtoArray
  status: 200
}
    
export type getMessagesResponseSuccess = (getMessagesResponse200) & {
  headers: Headers;
};
;

export type getMessagesResponse = (getMessagesResponseSuccess)

export const getGetMessagesUrl = (id: string,) => {


  

  return `/api/message/getMessages/${id}`
}

export const getMessages = async (id: string, options?: RequestInit): Promise<getMessagesResponse> => {
  
  const res = await fetch(getGetMessagesUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getMessagesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMessagesResponse
}





export const getGetMessagesQueryKey = (id: string,) => {
    return [
    `/api/message/getMessages/${id}`
    ] as const;
    }

    
export const getGetMessagesQueryOptions = <TData = Awaited<ReturnType<typeof getMessages>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessages>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMessagesQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMessages>>> = ({ signal }) => getMessages(id, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMessages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMessagesQueryResult = NonNullable<Awaited<ReturnType<typeof getMessages>>>
export type GetMessagesQueryError = unknown


export function useGetMessages<TData = Awaited<ReturnType<typeof getMessages>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessages>>,
          TError,
          Awaited<ReturnType<typeof getMessages>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessages<TData = Awaited<ReturnType<typeof getMessages>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessages>>,
          TError,
          Awaited<ReturnType<typeof getMessages>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessages<TData = Awaited<ReturnType<typeof getMessages>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessages>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMessages<TData = Awaited<ReturnType<typeof getMessages>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessages>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMessagesQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type postMessageResponse200 = {
  data: ApiResponseMessageResponseDto
  status: 200
}
    
export type postMessageResponseSuccess = (postMessageResponse200) & {
  headers: Headers;
};
;

export type postMessageResponse = (postMessageResponseSuccess)

export const getPostMessageUrl = (id: string,) => {


  

  return `/api/message/postMessage/${id}`
}

export const postMessage = async (id: string,
    partialIMessageDTO: PartialIMessageDTO, options?: RequestInit): Promise<postMessageResponse> => {
  
  const res = await fetch(getPostMessageUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      partialIMessageDTO,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postMessageResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postMessageResponse
}




export const getPostMessageMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postMessage>>, TError,{id: string;data: PartialIMessageDTO}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postMessage>>, TError,{id: string;data: PartialIMessageDTO}, TContext> => {

const mutationKey = ['postMessage'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postMessage>>, {id: string;data: PartialIMessageDTO}> = (props) => {
          const {id,data} = props ?? {};

          return  postMessage(id,data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostMessageMutationResult = NonNullable<Awaited<ReturnType<typeof postMessage>>>
    export type PostMessageMutationBody = PartialIMessageDTO
    export type PostMessageMutationError = unknown

    export const usePostMessage = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postMessage>>, TError,{id: string;data: PartialIMessageDTO}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postMessage>>,
        TError,
        {id: string;data: PartialIMessageDTO},
        TContext
      > => {
      return useMutation(getPostMessageMutationOptions(options), queryClient);
    }
    