/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ChatNest API
 * API for ChatNest chat application
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  MarkRead200,
  MarkReadBody,
  MessageResponseDto,
  PostMessageBody,
  SearchMessageResultDto,
  SearchParams,
  UserResponseDtoWithLastMessage
} from './chatNestAPI.schemas';

import { request } from '../request';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetUsersListUrl = () => {


  

  return `/api/message/getUsersListWithoutCurrentUser`
}

export const getUsersList = async ( options?: RequestInit): Promise<UserResponseDtoWithLastMessage[]> => {
  
  return request<UserResponseDtoWithLastMessage[]>(getGetUsersListUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetUsersListQueryKey = () => {
    return [
    `/api/message/getUsersListWithoutCurrentUser`
    ] as const;
    }

    
export const getGetUsersListQueryOptions = <TData = Awaited<ReturnType<typeof getUsersList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersList>>, TError, TData>>, request?: SecondParameter<typeof request>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersList>>> = ({ signal }) => getUsersList({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsersList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersListQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersList>>>
export type GetUsersListQueryError = unknown


export function useGetUsersList<TData = Awaited<ReturnType<typeof getUsersList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersList>>,
          TError,
          Awaited<ReturnType<typeof getUsersList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersList<TData = Awaited<ReturnType<typeof getUsersList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersList>>,
          TError,
          Awaited<ReturnType<typeof getUsersList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersList<TData = Awaited<ReturnType<typeof getUsersList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersList>>, TError, TData>>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUsersList<TData = Awaited<ReturnType<typeof getUsersList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersList>>, TError, TData>>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsersListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetMessagesUrl = (id: string,) => {


  

  return `/api/message/getMessages/${id}`
}

export const getMessages = async (id: string, options?: RequestInit): Promise<MessageResponseDto[]> => {
  
  return request<MessageResponseDto[]>(getGetMessagesUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetMessagesQueryKey = (id: string,) => {
    return [
    `/api/message/getMessages/${id}`
    ] as const;
    }

    
export const getGetMessagesQueryOptions = <TData = Awaited<ReturnType<typeof getMessages>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessages>>, TError, TData>>, request?: SecondParameter<typeof request>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMessagesQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMessages>>> = ({ signal }) => getMessages(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMessages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMessagesQueryResult = NonNullable<Awaited<ReturnType<typeof getMessages>>>
export type GetMessagesQueryError = unknown


export function useGetMessages<TData = Awaited<ReturnType<typeof getMessages>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessages>>,
          TError,
          Awaited<ReturnType<typeof getMessages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessages<TData = Awaited<ReturnType<typeof getMessages>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessages>>,
          TError,
          Awaited<ReturnType<typeof getMessages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessages<TData = Awaited<ReturnType<typeof getMessages>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessages>>, TError, TData>>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMessages<TData = Awaited<ReturnType<typeof getMessages>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessages>>, TError, TData>>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMessagesQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getMarkReadUrl = () => {


  

  return `/api/message/markRead`
}

export const markRead = async (markReadBody: MarkReadBody, options?: RequestInit): Promise<MarkRead200> => {
  
  return request<MarkRead200>(getMarkReadUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      markReadBody,)
  }
);}




export const getMarkReadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markRead>>, TError,{data: MarkReadBody}, TContext>, request?: SecondParameter<typeof request>}
): UseMutationOptions<Awaited<ReturnType<typeof markRead>>, TError,{data: MarkReadBody}, TContext> => {

const mutationKey = ['markRead'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof markRead>>, {data: MarkReadBody}> = (props) => {
          const {data} = props ?? {};

          return  markRead(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type MarkReadMutationResult = NonNullable<Awaited<ReturnType<typeof markRead>>>
    export type MarkReadMutationBody = MarkReadBody
    export type MarkReadMutationError = unknown

    export const useMarkRead = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markRead>>, TError,{data: MarkReadBody}, TContext>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof markRead>>,
        TError,
        {data: MarkReadBody},
        TContext
      > => {
      return useMutation(getMarkReadMutationOptions(options), queryClient);
    }
    export const getSearchUrl = (params: SearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/message/search?${stringifiedParams}` : `/api/message/search`
}

export const search = async (params: SearchParams, options?: RequestInit): Promise<SearchMessageResultDto[]> => {
  
  return request<SearchMessageResultDto[]>(getSearchUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getSearchQueryKey = (params?: SearchParams,) => {
    return [
    `/api/message/search`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getSearchQueryOptions = <TData = Awaited<ReturnType<typeof search>>, TError = unknown>(params: SearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>>, request?: SecondParameter<typeof request>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof search>>> = ({ signal }) => search(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchQueryResult = NonNullable<Awaited<ReturnType<typeof search>>>
export type SearchQueryError = unknown


export function useSearch<TData = Awaited<ReturnType<typeof search>>, TError = unknown>(
 params: SearchParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof search>>,
          TError,
          Awaited<ReturnType<typeof search>>
        > , 'initialData'
      >, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearch<TData = Awaited<ReturnType<typeof search>>, TError = unknown>(
 params: SearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof search>>,
          TError,
          Awaited<ReturnType<typeof search>>
        > , 'initialData'
      >, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearch<TData = Awaited<ReturnType<typeof search>>, TError = unknown>(
 params: SearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSearch<TData = Awaited<ReturnType<typeof search>>, TError = unknown>(
 params: SearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof search>>, TError, TData>>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getPostMessageUrl = (id: string,) => {


  

  return `/api/message/postMessage/${id}`
}

export const postMessage = async (id: string,
    postMessageBody?: PostMessageBody, options?: RequestInit): Promise<MessageResponseDto> => {
    const formData = new FormData();
if(postMessageBody?.text !== undefined) {
 formData.append(`text`, postMessageBody.text);
 }
if(postMessageBody?.image !== undefined) {
 formData.append(`image`, postMessageBody.image);
 }

  return request<MessageResponseDto>(getPostMessageUrl(id),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}




export const getPostMessageMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postMessage>>, TError,{id: string;data: PostMessageBody}, TContext>, request?: SecondParameter<typeof request>}
): UseMutationOptions<Awaited<ReturnType<typeof postMessage>>, TError,{id: string;data: PostMessageBody}, TContext> => {

const mutationKey = ['postMessage'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postMessage>>, {id: string;data: PostMessageBody}> = (props) => {
          const {id,data} = props ?? {};

          return  postMessage(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostMessageMutationResult = NonNullable<Awaited<ReturnType<typeof postMessage>>>
    export type PostMessageMutationBody = PostMessageBody
    export type PostMessageMutationError = unknown

    export const usePostMessage = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postMessage>>, TError,{id: string;data: PostMessageBody}, TContext>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postMessage>>,
        TError,
        {id: string;data: PostMessageBody},
        TContext
      > => {
      return useMutation(getPostMessageMutationOptions(options), queryClient);
    }
    