/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ChatNest API
 * API for ChatNest chat application
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  PickIUserSchemaExcludeKeyofIUserSchemaPassword
} from './chatNestAPI.schemas';

import { request } from '../request';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetUserListUrl = () => {


  

  return `/api/user/list`
}

export const getUserList = async ( options?: RequestInit): Promise<PickIUserSchemaExcludeKeyofIUserSchemaPassword[]> => {
  
  return request<PickIUserSchemaExcludeKeyofIUserSchemaPassword[]>(getGetUserListUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetUserListQueryKey = () => {
    return [
    `/api/user/list`
    ] as const;
    }

    
export const getGetUserListQueryOptions = <TData = Awaited<ReturnType<typeof getUserList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserList>>, TError, TData>>, request?: SecondParameter<typeof request>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserList>>> = ({ signal }) => getUserList({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserListQueryResult = NonNullable<Awaited<ReturnType<typeof getUserList>>>
export type GetUserListQueryError = unknown


export function useGetUserList<TData = Awaited<ReturnType<typeof getUserList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserList>>,
          TError,
          Awaited<ReturnType<typeof getUserList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserList<TData = Awaited<ReturnType<typeof getUserList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserList>>,
          TError,
          Awaited<ReturnType<typeof getUserList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserList<TData = Awaited<ReturnType<typeof getUserList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserList>>, TError, TData>>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUserList<TData = Awaited<ReturnType<typeof getUserList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserList>>, TError, TData>>, request?: SecondParameter<typeof request>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




